version: '3.6'

services:
  postgres:
    container_name: postgres
    image: postgres:11-alpine
    environment:
      # user='postgres' db='postgres'
      POSTGRES_PASSWORD: 123
    volumes:
      - ktor-boot-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  ktor-boot-db: